version: '3'

services:
  database:
    image: 'mysql:5.7'
    container_name: 'mysql'
    restart: 'always'
    command: 'mysqld --max-connections=1000 --sql-mode="ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_FIELD_OPTIONS,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,ANSI,DB2,MAXDB,MSSQL,MYSQL323,MYSQL40,ORACLE,POSTGRESQL,TRADITIONAL"'
    networks:
      - 'prisma'
    env_file: './.mysql.env'
    ports:
      - '3306:3306'
    volumes:
      - 'volume-database:/var/lib/mysql'

  prisma:
    image: 'prismagraphql/prisma:1.3-beta'
    container_name: "prisma"
    restart: 'always'
    ports:
      - '0.0.0.0:4466:4466'
    depends_on:
      - 'database'
    networks:
      - 'prisma'
    env_file: './.prisma.env'

networks:
  prisma:
    driver: "bridge"

volumes:
  volume-database: